name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '20*' # 2023.1.17f1

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      target: unity-portable-${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      
      - name: lessmsi 
        shell: cmd
        run: | 
          curl https://download.unity3d.com/download_unity/b84c4024cd38/Windows64EditorInstaller/UnitySetup64-2023.1.17f1.exe -L --output installer.exe

      - shell: cmd
        run: |
          .\installer.exe /S /D=%cd%\installation

      - shell: cmd
        run: |
          md export &&^
          7z a -tzip -v100m export\${{ env.target }} installation

      - shell: cmd
        run: |
          dir /s
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "export/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
